In [212]:
import math
import numpy as np
from random import randrange

n = 3

def LatticeVectorGen(n):
    a = [randrange(1,5) for i in range(n)]
    b = [randrange(1,5) for i in range(n)]
    c = [randrange(1,5) for i in range(n)]
    return a,b,c
    
def vectorlength(a):
    g = 0
    for i in a:
        b = i*i
        g += b
    h = math.sqrt(g)
    return h

def GramSchmidt(a,b,c):
    moda = vectorlength(a)
    print(a)
    bprime = np.subtract(b,np.multiply((np.dot(a,b)/moda*moda),a)).tolist()
    print(bprime)
    modbprime = vectorlength(bprime)
    difference = np.add(np.multiply((np.dot(a,c)/(moda*moda)),a),np.multiply((np.dot(bprime,c)/(modbprime*modbprime)),bprime))
    print(f"diff{difference}")
    print(c)
    cprime = np.subtract(c,difference)
    print(cprime)
    return (a,bprime,cprime)

def OrthGen(n):
    a,b,c = LatticeVectorGen(n)
    v1,v2,v3 = GramSchmidt(a,b,c)
    return v1,v2,v3

def checkOrth(a,b):
    print(a)
    print(b)
    moda = vectorlength(a)
    modb = vectorlength(b)
    g = np.arccos(np.divide(np.dot(a,b),np.multiply(moda,modb)))
    if g - math.pi < 0.1 and g - math.pi > -0.1:
        return True , g
    else:
        return False , g

v1,v2,v3 = OrthGen(n)
#checkOrth(v1,v2)
checkOrth(v1,v3)

[2, 2, 2]
[-29.0, -30.0, -29.0]
diff[5.28363026 5.37387038 5.28363026]
[4, 1, 3]
[-1.28363026 -4.37387038 -2.28363026]
[2, 2, 2]
[-1.28363026 -4.37387038 -2.28363026]


(False, 2.688893727409405)

In [195]:
a = [1,2,3]
b = [4,5,6]

def vectorlength(a):
    g = 0
    for i in a:
        b = i*i
        g += b
    h = math.sqrt(g)
    return h

np.multiply((np.dot(a,b)/(vectorlength(a)*vectorlength(a))),a)

array([2.28571429, 4.57142857, 6.85714286])

In [201]:
a = [1,2,3]
b = [4,5,6]

np.add(a,b)

array([5, 7, 9])

In [114]:
from random import randrange
randrange(1,7)

6